name: C/C++ CI

on:
  push:
    branches: 
      - main
      - 'dev_**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cross-compiler
      run: |
        # sudo apt update
        # sudo apt -y upgrade
        # sudo apt install curl
        ARM_TOOLCHAIN_VERSION=$(curl -s https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads | grep -Po '<h4>Version \K.+(?=</h4>)')
        curl -Lo aarch64-none-elf.tar.xz "https://developer.arm.com/-/media/Files/downloads/gnu/${ARM_TOOLCHAIN_VERSION}/binrel/arm-gnu-toolchain-${ARM_TOOLCHAIN_VERSION}-x86_64-aarch64-none-elf.tar.xz"
        sudo mkdir /opt/gcc-arm
        sudo tar xf aarch64-none-elf.tar.xz --strip-components=1 -C /opt/gcc-arm
        echo 'export PATH=$PATH:/opt/gcc-arm/bin' | sudo tee -a /etc/profile.d/aarch64-none-elf.sh
    - name: make
      run: |
        source /etc/profile 
        make
